@startuml

title __MODEL's Class Diagram__\n

  namespace model {
    class model.Recensione {
        - autore : String
        - dataRecensione : String
        - idRecensione : int
        - statoRecensione : String
        - struttura : int
        - testo : String
        - titolo : String
        - valutazione : int
        + getAutore()
        + getDataRecensione()
        + getIdRecensione()
        + getStatoRecensione()
        + getStruttura()
        + getTesto()
        + getTitolo()
        + getValutazione()
        + setAutore()
        + setDataRecensione()
        + setIdRecensione()
        + setStatoRecensione()
        + setStruttura()
        + setTesto()
        + setTitolo()
        + setValutazione()
    }
  }
  

  namespace model {
    class model.Struttura {
        - categoria : String
        - città : String
        - descrizione : String
        - fasciaDiPrezzo : String
        - idStruttura : int
        - indirizzo : String
        - latitudine : double
        - longitudine : double
        - nome : String
        - urlFoto : String
        - valutazioneMedia : double
        + getCategoria()
        + getCittà()
        + getDescrizione()
        + getFasciaDiPrezzo()
        + getIdStruttura()
        + getIndirizzo()
        + getLatitudine()
        + getLongitudine()
        + getNome()
        + getUrlFoto()
        + getValutazioneMedia()
        + setCategoria()
        + setCittà()
        + setDescrizione()
        + setFasciaDiPrezzo()
        + setIdStruttura()
        + setIndirizzo()
        + setLatitudine()
        + setLongitudine()
        + setNome()
        + setUrlFoto()
        + setValutazioneMedia()
    }
  }
  

  namespace model {
    class model.Utente {
        - dataDiNascita : String
        - email : String
        - mostraNickname : boolean
        - nickname : String
        - nome : String
        - password : String
        - salt : String
        + getDataDiNascita()
        + getEmail()
        + getNickname()
        + getNome()
        + getPassword()
        + getSalt()
        + isMostraNickname()
        + setDataDiNascita()
        + setEmail()
        + setMostraNickname()
        + setNickname()
        + setNome()
        + setPassword()
        + setSalt()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
