@startuml

title __APP's Class Diagram__\n

  namespace DAO {
    class DAO.RecensioneDAO {
    }
  }
  

  namespace DAO {
    class DAO.StrutturaDAO {
    }
  }
  

  namespace DAO {
    class DAO.UtenteDAO {
    }
  }
  

  namespace DAO {
    interface DAO.VolleyCallback {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.AggiungiRecensioneFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.BuildConfig {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.ConnessioneAssenteFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.CustomSupportMapFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.DettagliStrutturaFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.Filtri {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.FiltriFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.ListaRecensioniRecycleViewAdapter {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.ListaStruttureFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.ListaStruttureRecyclerViewAdapter {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.LoginFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.MainActivity {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.NessunaStrrutturaTrovataFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.PasswordUtils {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.SignupFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.VisualizzaRecensioneFragment {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.VisualizzaStrutturaSuMappa {
    }
  }
  

  namespace com.example.provacv {
    class com.example.provacv.VisualizzaSuMappaDialog {
    }
  }
  

  namespace model {
    class model.Recensione {
    }
  }
  

  namespace model {
    class model.Struttura {
    }
  }
  

  namespace model {
    class model.Utente {
    }
  }
  

  com.example.provacv.AggiungiRecensioneFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.AggiungiRecensioneFragment o-- DAO.RecensioneDAO : recensioneDAO
  com.example.provacv.ConnessioneAssenteFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.CustomSupportMapFragment -up-|> com.mapbox.mapboxsdk.maps.SupportMapFragment
  com.example.provacv.DettagliStrutturaFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.DettagliStrutturaFragment o-- DAO.RecensioneDAO : recensioneDAO
  com.example.provacv.FiltriFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.FiltriFragment o-- com.example.provacv.MainActivity : activity
  com.example.provacv.FiltriFragment o-- DAO.StrutturaDAO : strutturaDAO
  com.example.provacv.ListaRecensioniRecycleViewAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.provacv.ListaRecensioniRecycleViewAdapter o-- com.example.provacv.MainActivity : mainActivity
  com.example.provacv.ListaStruttureFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.ListaStruttureRecyclerViewAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.provacv.ListaStruttureRecyclerViewAdapter o-- com.example.provacv.MainActivity : mainActivity
  com.example.provacv.LoginFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.LoginFragment o-- com.example.provacv.MainActivity : mainActivity
  com.example.provacv.LoginFragment o-- DAO.UtenteDAO : utenteDAO
  com.example.provacv.MainActivity .up.|> com.google.android.material.navigation.NavigationView.OnNavigationItemSelectedListener
  com.example.provacv.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.provacv.MainActivity o-- DAO.StrutturaDAO : strutturaDao
  com.example.provacv.NessunaStrrutturaTrovataFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.SignupFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.SignupFragment o-- DAO.UtenteDAO : utenteDAO
  com.example.provacv.VisualizzaRecensioneFragment -up-|> androidx.fragment.app.Fragment
  com.example.provacv.VisualizzaRecensioneFragment o-- model.Recensione : recensione
  com.example.provacv.VisualizzaStrutturaSuMappa -up-|> androidx.fragment.app.Fragment
  com.example.provacv.VisualizzaStrutturaSuMappa o-- model.Struttura : struttura
  com.example.provacv.VisualizzaSuMappaDialog -up-|> androidx.fragment.app.DialogFragment
  com.example.provacv.VisualizzaSuMappaDialog o-- model.Struttura : strutturaSelezionata


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
